apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: redis
  namespace: microbean
spec:
  serviceClassName: stable--redis
  planName: free--stable--redis
  parameters:
    helm:
      namespace: microbean
    persistence:
      enabled: false
